<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>home</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <img src="10.jpg" alt="perfume">
    <h5>Perfume</h5>
    <h6>Patrick Suskind</h6>
    <p>Sinopsis : Jean-Baptiste Grenouille adalah seorang lelaki yatim piatu yang memiliki indera penciuman tajam. Mulanya dia hidup bersama ibunya, namun sang ibu mendapatkan hukuman mati di kemudian hari. Kehidupan kecil Grenouille serba kekurangan. Dia tinggal pada lingkungan kumuh di Prancis. Dia lantas tumbuh bersama anak lainnya di panti asuhan. Saat menginjak remaja, Grenouille mulai membanting tulang dengan memilih pekerjaan sebagai buruh kasar. Sampai suatu hari, hidungnya mengenali sebuah aroma yang menurutnya sangat menarik dan langka saat diajak majikannya mengantar barang. Grenouille tertarik dengan aroma itu dan lantas mencari sumbernya. Tak disangka, aroma tersebut keluar dari tubuh seorang gadis penjual buah plum. Rasa penasaran Grenouille terhadap aroma ini membuatnya tidak sengaja membunuh si gadis. Grenouille tidak langsung mengubur tapi justru membuka pakaian si gadis dan membaui tubuhnya untuk mencari letak sumber aroma langka itu. Upaya Grenouille ternyata gagal. Dia pun makin penasaran dengan dunia aroma di sekitarnya. Lalu, Grenouille mulai mendapatkan pekerjaan di toko kepunyaan Baldini. Di sana, Grenouille meracik berbagai bibit parfum untuk mendapatkan aroma-aroma sedap. Toko Baldini yang mulanya hampir gulung tikarnya, akhirnya bangkit kembali berkat kepiawaian Grenouille meracik parfum. Meski Grenouille telah berhasil membuat banyak aroma, namun dia masih penasaran dengan aroma yang dimiliki gadis penjual buah. Baldini yang melihat obsesi besar Grenouille tersebut, lantas memberikan petunjuk demi memperoleh ramuan parfum sempurna. Baldini menyarankannya pergi ke Grasse. Dari sinilah, Grenouille mulai menjadi psikopat untuk mewujudkan impiannya. Sampai di Kota Grasse, Grenouille mulai memperdaya banyak gadis. Dia membunuh setiap gadis yang berhasil ditipu, lalu mengambil sari tubuh mereka untuk dijadikan bibit parfum. Sari tubuh ini diekstrak dari pakaian, rambut, sampai kulit kepala. Tubuh 25 gadis yang dibunuh Grenouille tampak sangat layu seakan tidak pernah hidup sebelumnya. Kendati Grenouille telah melakukan peracikan menggunakan banyak sari tubuh mereka, aroma parfum yang diinginkannya belum juga didapatkan. Peluang Grenouille untuk mewujudkan parfum sempurna kembali datang setelah bertemu Laura Richis. Gadis ini memiliki aroma badan mirip gadis penjual buah. Grenouille mulai melancarkan usaha untuk memperdaya Laura yang merupakan anak pengusaha kaya bernama Antoine Richis. Akankah Grenouille berhasil membunuh Laura dan mengambil sari tubuhnya? Baca selengkapnya di artikel "Sinopsis & Streaming "Perfume The Story of A Murderer" di Netflix", https://tirto.id/grSJ</p>
</body>
</html>